package rcteam.rc2.rollercoaster;

public enum TrackTypeEnum {
	WOODEN,
	WOODEN_WILD_MOUSE,
	STEEL_MINI,
	STEEL,
	STEEL_STANDUP,
	STEEL_CORKSCREW,
	MINE_TRAIN,
	SUSPENDED,
	SUSPENDED_SINGLE_RAIL,
	INVERTED,
	BOBSLED,
	REVERSE_WHOA_BELLY,
	VERTICAL;

	private TrackTypeEnum() {}
}
